name: Python package

on:

  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - reopened
      - synchronize
    
jobs:
  check-commit-message:
    name: Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Jira ID
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'TASK-[0-9]'
          flags: 'gm'
          error: 'ERROR in commit message'
